language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: 21f42f6c-ec4f-4755-9c3d-f90111aedc20
  app: sheltered-fortress-34693
  on:
    repo: race-briggs/meme-dream
