language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: 9335e9a1-f68f-4624-a42b-bd810e966854
  app: sheltered-fortress-34693
  on:
    repo: race-briggs/meme-dream
